routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// PANEL ROUTES

Route::group(["namespace" => "Panel", "prefix" => "panel", "middleware" => ["auth", "admin"]],function (){

    Route::get('dashboard', 'DashboardController@index')->name("dashboard");

    Route::get("options", "OptionController@edit")->name("options.edit");
    Route::put("options/update/{id}", "OptionController@update")->name("options.update");

    Route::resource("users", "UserController");
    Route::post("updateUserStatus", "UserController@updateUserStatus")->name("updateUserStatus");

    Route::resource("product-categories", "ProductCategoryController");
    Route::post("product-categories/update-category-status", "ProductCategoryController@updateStatus")->name("updateProductCategoryStatus");

    Route::resource("products", "ProductController");

    Route::get("product-images", "ProductImageController@index")->name("product-images.index");
    Route::post("product-images/store", "ProductController@storeProductImage")->name("product-images.store");
    Route::post("updateProductStatus", "ProductController@updateStatus")->name("updateProductStatus");
    Route::delete("product-images/{id}", "ProductImageController@destroy")->name("product-images.destroy");

    Route::resource("pages","PageController");
    Route::post("updatePageStatus", "PageController@updateStatus")->name("updatePageStatus");


    Route::resource("blog-categories","BlogCategoryController");
    Route::post("updateBlogCategoryStatus", "BlogCategoryController@updateStatus")->name("updateBlogCategoryStatus");


    Route::resource("blogs","BlogController");
    Route::post("updateBlogStatus", "BlogController@updateStatus")->name("updateBlogStatus");

    Route::resource("sliders", "SliderController");
    Route::post("updateSliderStatus", "SliderController@updateStatus")->name("updateSliderStatus");

    Route::resource("universities", "UniversityController");
    Route::post("updateUniversityStatus", "UniversityController@updateStatus")->name("updateUniversityStatus");

    Route::get("faculties/{id}", "FacultyController@index")->name("faculties.index");
    Route::get("faculties/create/{id}", "FacultyController@create")->name("faculties.create");
    Route::get("faculties/edit/{parentID}/{id}", "FacultyController@edit")->name("faculties.edit");
    Route::put("faculties/update/{parentID}/{id}", "FacultyController@update")->name("faculties.update");
    Route::post("faculties/store", "FacultyController@store")->name("faculties.store");
    Route::delete("faculties/delete/{id}", "FacultyController@destroy")->name("faculties.destroy");
    Route::post("updateFacultyStatus", "FacultyController@updateStatus")->name("updateFacultyStatus");
});

Route::get("logout", function (){
    Auth::logout();

    return redirect()->route("login");
});

Auth::routes(["verify" => true, "register" => false]);

Route::get('/home', 'HomeController@index')->name('home');

// FRONT ROUTES


Route::group(["namespace" => "Front"],function (){

    Route::get("/", "HomeController@index")->name("front.index");

    Route::get("kategori/{slug}", "CategoryController@index")->name("front.category");

    Route::get("blog", "BlogController@index")->name("front.get-all-blog");
    Route::get("blog/{slug}","BlogController@detail")->name("front.blog-detail");
    Route::get("blog/kategori/{slug}", "BlogController@getBlogsByCategory")->name("front.get-blogs-by-category");

    Route::post("blog/add-comment", "CommentController@store")->name("front.add-blog-comment");

    Route::get("urunler", "ProductController@index")->name("front.product-list");
    Route::get("urun/{slug}", "ProductController@detail")->name("front.product-detail");
    Route::post("urunler/ara", "ProductController@search")->name("front.search-product");

    Route::get("giris-yap", "AuthenticationController@index")->name("front.authentication");
    Route::post("giris-yap","AuthenticationController@login")->name("front.login");
    Route::post("kullanici-islemleri/kaydol","AuthenticationController@register")->name("front.register");

    Route::get("kullanici-islemleri/dogulama-kodu/{email}", "AuthenticationController@verifyCode")->name("front.verify-code");
    Route::post("kullanici-islemleri/dogrula", "AuthenticationController@verify")->name("front.verify");
    Route::post("kullanici-islemleri/tekrar-dogrula/{userId}", "AuthenticationController@reVerify")->name("front.re-verify");
    Route::get("kullanici-islemleri/cikis-yap", "AuthenticationController@logout")->name("front.logout");

    Route::get("profil/{userId}", "UserController@profile")->name("front.profile");
    Route::put("profil/güncelle/{id}", "UserController@update")->name("front.update-user");

    Route::get("urun-ekle/birinci-adim", "ProductController@create")->name("front.create-product");
    Route::post("urun-ekle/ikinci-adim", "ProductController@stepTwo")->name("front.product-step-two");
    Route::post("urun-ekle/kaydet", "ProductController@completeSteps")->name("front.product-complete-steps");

    Route::delete("urun-sil/{id}", "ProductController@destroy")->name("front.delete-product");

    Route::get("urun-duzenle/birinci-adim/{id}", "ProductController@edit")->name("front.edit-product");
    Route::put("urun-duzenle/ikinci-adim/{id}", "ProductController@editStepTwo")->name("front.edit-product-step-two");
    Route::put("urun-duzenle/tamamla/{id}", "ProductController@update")->name("front.update-product");
    Route::delete("urun-duzenle/resim-sil/{id}", "ProductController@deleteImage")->name("front.delete-product-image");

    Route::get("iletisim", "ContactController@contactPage")->name("front.contact-page");
    Route::post("iletisim/gonder", "ContactController@sendContactMessage")->name("front.contact");

    Route::post("sendMailToSeller", "ContactController@sendMailToSeller")->name("front.send-mail-to-seller");


    Route::get("testEmail", function (){
        return frontView("authentication.verify")->with(["title" => "verify", "message" => "uyarı mesajı", "user_email" => "asd"]);
    });
});

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

class Blog extends Model
{
    protected $guarded = ["id"];
    protected $fillable = ["title", "slug", "image", "description", "content", "is_active", "user_id", "category_id"];

    public function category(){
        return $this->belongsTo(BlogCategory::class, "category_id");
    }

    public function comments(){
        return $this->hasMany(BlogComment::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function getShortenDescriptionAttribute(){

        return Str::limit($this->content, 70, "...");

    }

    public function getModifiedDateAttribute($created_at){

        $carbon = new Carbon();
        $carbon->locale("tr");
        return $carbon->diffForHumans($this->attributes["created_at"]);
    }

    public function getShortenContentAttribute(){
        return Str::limit(strip_tags($this->content), 444, "...");
    }
}

app/Http/Controllers/Front/BlogController.php
<?php

namespace App\Http\Controllers\Front;

use App\BlogComment;
use App\Http\Controllers\Controller;
use App\Repositories\Classes\BlogCategoryRepository;
use App\Repositories\Classes\BlogRepository;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    private  $blogRespository = null;
    private  $categoryRepository = null;
    private  $resource = "blog";

    public function __construct()
    {
        $this->blogRespository = new BlogRepository();
        $this->categoryRepository = new BlogCategoryRepository();
    }

    public function index(){

        $data = [
            "title" => "Blog Yazılarımız",
            "blogs" => $this->blogRespository->getAll("id", "desc")
        ];

        return frontView("$this->resource.blog-list")->with($data);

    }

    public function detail($slug){

        $blog = $this->blogRespository->getBySlug($slug);
        $comments = $blog->comments;
        $similarPosts = $this->blogRespository->getAllWithWhere("id","!=", $blog->id);

        $data = [
            "title" => $blog->title,
            "blog"  => $blog,
            "similarPosts" => $similarPosts,
            "comments"     => $comments
        ];

        return frontView("$this->resource.blog-detail")->with($data);
    }

    public function getBlogsByCategory($slug)
    {
        $category = $this->categoryRepository->getBySlug($slug);
        dd($category);
    }
}

app/Http/Controllers/Panel/BlogCategoryController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Enums\BlogEnums;
use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\Repositories\Classes\BlogCategoryRepository;
use App\Traits\GeneralCrud;
use App\Traits\StatusUpdater;
use Illuminate\Http\Request;

class BlogCategoryController extends Controller
{
    use GeneralCrud, StatusUpdater;
    private $repository = null;
    private $pageEnum   = null;
    private $resource   = null;

    public function __construct()
    {
        $this->repository = new BlogCategoryRepository();
        $this->pageEnum   = new BlogEnums();
        $this->resource   = "blog-categories";
    }
    public function index()
    {
        $data = [
            "title"    => "Blog Kategorisi Yönetimi",
            "categories"    => $this->repository->getAll(),
            "isActive" => $this->pageEnum::_ACTIVE,
        ] ;

        return panelView("$this->resource.index")->with($data);
    }


    public function create()
    {
        $data = [
            "title" => "Yeni Blog Kategorisi Oluştur",
        ];

        return panelView("$this->resource.create")->with($data);
    }

    public function edit($id)
    {
        $category = $this->repository->getById($id);

        $data = [
            "title" => $category->title .  " Kategorisi Düzenleniyor",
            "category"  => $category
        ];

        return panelView("$this->resource.edit")->with($data);
    }
}

app/Http/Controllers/Panel/BlogController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Enums\BlogEnums;
use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\Blog\BlogStoreRequest;
use App\Http\Requests\Blog\BlogUpdateRequest;
use App\Repositories\Classes\BlogCategoryRepository;
use App\Repositories\Classes\BlogRepository;
use App\Traits\GeneralCrud;
use App\Traits\StatusUpdater;
use Illuminate\Http\Request;
use Mmurattcann\LaraImage\LaraImage;

class BlogController extends Controller
{
    use GeneralCrud, StatusUpdater;

    private $repository = null;
    private $categoryRepository = null;
    private $enum   = null;
    private $resource   = null;
    private $uploadPath = "uploads/blogs";
    public function __construct()
    {
        $this->repository = new BlogRepository();
        $this->categoryRepository = new BlogCategoryRepository();
        $this->enum   = new BlogEnums();
        $this->resource   = "blogs";
    }
    public function index()
    {
        $data = [
            "title"    => "Blog Yönetimi",
            "blogs"    => $this->repository->getAll(),
            "isActive" => $this->enum::_ACTIVE,
        ] ;

        return panelView("$this->resource.index")->with($data);
    }


    public function create()
    {
        $data = [
            "title" => "Yeni Sayfa Oluştur",
            "categories" => $this->categoryRepository->getAll("title", "asc")
        ];

        return panelView("$this->resource.create")->with($data);
    }

    public function edit($id)
    {
        $blog = $this->repository->getById($id);

        $data = [
            "title" => $blog->title .  " Blogu Düzenleniyor",
            "blog"  => $blog,
            "categories" => $this->categoryRepository->getAll("title","asc")
        ];

        return panelView("$this->resource.edit")->with($data);
    }

}

app/Http/Controllers/Panel/DashboardController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use App\Repositories\Classes\BlogRepository;
use App\Repositories\Classes\ProductRepository;
use App\Repositories\Classes\UniversityRepository;
use App\Repositories\Classes\UserRepository;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    private $productRepository = null;
    private $userRepository = null;
    private $blogRepository = null;
    private $universityRepository = null;

    public function __construct()
    {
        $this->productRepository = new ProductRepository();
        $this->userRepository    = new UserRepository();
        $this->blogRepository    = new BlogRepository();
        $this->universityRepository = new UniversityRepository();
    }

    public function index(){

        $lastProducts = $this->productRepository->baseQuery()->take(5)->latest()->get();
        $lastUsers    = $this->userRepository->baseQuery()->take(5)->latest()->get();

        $totalProducts = $this->productRepository->baseQuery()->count();
        $totalBlogs    = $this->blogRepository->baseQuery()->count();
        $totalUsers    = $this->userRepository->baseQuery()->count();
        $totalUniversities =  $this->universityRepository->baseQuery()->count();

        $data = [
            "title" => "Yönetim Ana Sayfa| İstatistikler",
            "lastProducts" => $lastProducts,
            "lastUsers" => $lastUsers,
            "blogCount" =>  $totalBlogs,
            "userCount" => $totalUsers,
            "productCount" => $totalProducts,
            "universityCount" => $totalUniversities
        ];
        return panelView("dashboard.index")->with($data);
    }
}

app/Http/Controllers/Panel/FacultyController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Enums\BlogEnums;
use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\Repositories\Classes\FacultyRepository;
use App\Repositories\Classes\UniversityRepository;
use App\Traits\GeneralCrud;
use App\Traits\StatusUpdater;
use Illuminate\Http\Request;

class FacultyController extends Controller
{
    use StatusUpdater;

    private $repository = null;
    private $universityRepository = null;
    private $resource = "faculties";

    public function __construct()
    {
        $this->repository = new FacultyRepository();
        $this->universityRepository = new UniversityRepository();
    }

    public function index($id){

        $university = $this->universityRepository->getById($id);
        $data = [
            "title" => $university->title. " Fakülte Listesi",
            "university" => $university,
            "faculties" => $university->faculties,
            "isActive" => BlogEnums::_ACTIVE
        ];

        return panelView("$this->resource.index")->with($data);
    }

    public function create($id){
        $university = $this->universityRepository->getById($id);

        $data = [
            "title" => "Yeni Fakülte Kaydı",
            "university" => $university
        ];

        return panelView("$this->resource.create")->with($data);
    }

    public function store(Request $request){

        $university_id = $request->get("university_id");
        $this->repository->store($request);
        return RedirectHelper::RedirectWithSuccessFlashMessage("store", "$this->resource.index", ["id" => $university_id]);
    }
    public function edit($parentID, $id){

        $university = $this->universityRepository->getById($id);
        $faculty = $this->repository->getById($id);

        $data = [
            "title" => $faculty->title. " Fakültesi Düzenleniyor",
            "university" => $university,
            "faculty" => $faculty
        ];

        return panelView("$this->resource.edit")->with($data);
    }

    public function update(Request $request, $parentID, $id){
        $university_id = $request->get("university_id");
        $this->repository->update($request, $id);
        return RedirectHelper::RedirectWithSuccessFlashMessage("store", "$this->resource.index", ["id" => $university_id]);
    }

    public function destroy($id){
        $this->repository->destroy($id);
        return response()->json(["message" => "Kayıt Başarıyla Silindi"], 200);
    }
}

app/Http/Controllers/Panel/OptionController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\Repositories\Classes\OptionRepository;
use Illuminate\Http\Request;

class OptionController extends Controller
{
    public $repository = null;
    public $resource   = "options";

    public function __construct()
    {
        $this->repository = new OptionRepository();
    }

    public function edit()
    {
        $option = $this->repository->getFirst();

        $data = [
            "title"   => "Site Ayarları",
            "option" => $option,
            "route"   => route("$this->resource.update", ["id" => $option->id])
        ];

        return panelView("$this->resource.edit")->with($data);

    }
    public function update(Request $request, $id)
    {
        $this->repository->update($request, $id);
        return RedirectHelper::RedirectWithSuccessFlashMessage("update","options.edit");
    }
}

resources/views/panel/blogs/create.blade.php
@extends("layouts.panel._layout")
@section("title")
    {{$title}}
@endsection

@push("css")

    <!-- select2 Plugin -->
    <link href="{{panelAsset("plugins/select2/select2.min.css")}}" rel="stylesheet" />
    <!-- WYSIWYG Editor css -->
    <link href="{{panelAsset('plugins/wysiwyag/richtext.css')}}" rel="stylesheet">
@endpush

@section("content")
    <ol class="breadcrumb breadcrumb-arrow mt-3 mb-3">
    </ol>

    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{$title}}</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form action="{{route("blogs.store")}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method("POST")
                                <input type="hidden" name="is_active" value="1">

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <div class="form-label">Kapak Resmi</div>
                                            <div class="custom-file">
                                                <input type="file" class="custom-file-input" name="image">
                                                <label class="custom-file-label">Seç</label>
                                            </div>

                                            @error("image")
                                            <span class="text-danger">{{$message}}</span>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group col-md-6">
                                        <label class="form-label">Kategori</label>
                                        <select name="category_id" class="form-control">
                                            <option value="">--- Kategori Seçin --- </option>
                                            @foreach($categories as $category)
                                                <option value="{{$category->id}}">{{$category->title}}</option>
                                            @endforeach
                                        </select>
                                        @error("category_id")
                                        <span class="text-danger">{{$message}}</span>
                                        @enderror
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label class="form-label">Başlık</label>
                                        <input type="text" class="form-control" name="title" placeholder="Başlık" value="{{old("title")}}">
                                        @error("title")
                                            <span class="text-danger">{{$message}}</span>
                                        @enderror
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label class="form-label">Slug</label>
                                        <input type="text" class="form-control" name="slug" placeholder="slug" value="{{old("slug")}}">
                                        @error("slug")
                                            <span class="text-danger">{{$message}}</span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label class="form-label">SEO Açıklaması</label>
                                        <textarea class="form-control" name="description" placeholder="SEO Açıklaması">
                                        {{old("description")}}
                                    </textarea>
                                        @error("description")
                                        <span class="text-danger">{{$message}}</span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="form-label">İçerik</label>
                                    <textarea class="form-control content richText-initial" name="content" placeholder="İçerik">
                                        {{old("content")}}
                                    </textarea>
                                    @error("content")
                                    <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                               {{-- <div class="form-group ">
                                    <label class="form-label">Kullanıcı Rolü</label>
                                    <select class="form-control select2 custom-select" name="role">

                                        <option value="{{$standardUserEnum}}">Standart Kullanıcı</option>
                                        <option value="{{$adminEnum}}">Admin</option>
                                    </select>
                                    @error("role")
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>--}}
                                <button class="btn btn-primary btn-lg mt-5 mb-5" type="submit">Kaydet</button>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push("js")

    <!--Select2 js -->
    <script src="{{panelAsset("plugins/select2/select2.full.min.js")}}"></script>
    <script src="{{panelAsset("js/select2.js")}}"></script>
    <!-- WYSIWYG Editor js -->
    <script src="{{panelAsset('plugins/wysiwyag/jquery.richtext.js')}}"></script>
    <script src="{{panelAsset('plugins/wysiwyag/richText1.js')}}"></script>
@endpush

resources/views/panel/blogs/index.blade.php
@extends("layouts.panel._layout")
@section("title")
{{$title}}
@endsection
@push("css")
    <!-- Data table css -->
    <link href="{{panelAsset("plugins/datatable/dataTables.bootstrap4.min.css")}}" rel="stylesheet" />
    <!-- Bootstrap Toggle css -->
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">

    <!---Sweetalert Css-->
    <link href="{{panelAsset("plugins/sweet-alert/jquery.sweet-modal.min.css")}}" rel="stylesheet" />
    <link href="{{panelAsset("plugins/sweet-alert/sweetalert.css")}}" rel="stylesheet" />
@endpush

@section("content")
    <div class="container">
        <ol class="breadcrumb breadcrumb-arrow mt-3">
        </ol>
        <div class="page-header">
            <h4 class="page-title">{{$title}}</h4>
            <a href="{{route("blogs.create")}}" class="btn btn-primary btn-lg pull-right"><i class="fa fa-user-plus"></i> Yeni Kayıt</a>

        </div>
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">{{$title}} </div>
                    </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="users-table" class="table table-striped table-bordered w-100">
                            <thead>
                                <tr>
                                    <th class="wd-15p">#ID</th>
                                    <th class="wd-15p">Görsel</th>
                                    <th class="wd-15p">Başlık</th>
                                    <th class="wd-10p">Slug</th>
                                    <th class="wd-20p">SEO Açıklaması</th>
                                    <th class="wd-20p">Kategori</th>
                                    <th class="wd-10p">Durum</th>
                                    <th class="wd-50p">İşlemler</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($blogs as $blog)
                                <tr id="tr-{{$blog->id}}">
                                    <td>{{$blog->id}}</td>
                                    <td>
                                        <img src="{{getBlogCover($blog->image)}}" alt="{{$blog->title}}" class="img-responsive" style="width: 125px; height: 100px">
                                    </td>
                                    <td>{{$blog->title}}</td>
                                    <td>{{$blog->slug}}</td>
                                    <td>{{$blog->shorten_description}}</td>
                                    <td>
                                        <span class="bg-gradient-teal" style="color:white; padding: 3px">{{$blog->category->title}}</span>
                                    </td>
                                    <td>
                                        <input type="checkbox"
                                               name="is_active"
                                               id="is_active"
                                               class="is_active"
                                               data-id="{{$blog->id}}"
                                               data-toggle="toggle"
                                               data-on="Aktif"
                                               data-off="Pasif"
                                               data-onstyle="success"
                                               data-offstyle="danger"
                                               data-route="{{route("updateBlogStatus")}}"
                                               @if($blog->is_active == $isActive) checked @endif
                                        >
                                    </td>
                                    <td>
                                        <a href="{{route('blogs.edit', $blog->id)}}" class="btn btn-outline-success" ><i class="fa fa-pencil-square-o fa-3x"></i></a>
                                        <button class="btn btn-danger delete-button" data-id="{{$blog->id}}" data-route="{{route("blogs.destroy", $blog->id)}}" >Sil</button>

                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- table-wrapper -->
            </div>
            <!-- section-wrapper -->

        </div>
    </div>
    </div>
@endsection

@push("js")
    <!-- Bootstrap Toggle -->
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

    <!-- Data tables -->
    <script src="{{panelAsset("plugins/datatable/jquery.dataTables.min.js")}}"></script>
    <script src="{{panelAsset("plugins/datatable/dataTables.bootstrap4.min.js")}}"></script>
    <script src="{{panelAsset("plugins/datatable/datatable.js")}}"></script>
    <!-- Sweet alert Plugin -->
    <script src="{{panelAsset("plugins/sweet-alert/jquery.sweet-modal.min.js")}}"></script>
    <script src="{{panelAsset("plugins/sweet-alert/sweetalert.min.js")}}"></script>
    <script src="{{panelAsset("js/sweet-alert.js")}}"></script>

    <!-- User CRUD Operations-->
    <script src="{{panelAsset("CustomOperations/userCrud.js")}}"></script>

@endpush