routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// PANEL ROUTES

Route::group(["namespace" => "Panel", "prefix" => "panel", "middleware" => ["auth", "admin"]],function (){

    Route::get('dashboard', 'DashboardController@index')->name("dashboard");

    Route::get("options", "OptionController@edit")->name("options.edit");
    Route::put("options/update/{id}", "OptionController@update")->name("options.update");

    Route::resource("users", "UserController");
    Route::post("updateUserStatus", "UserController@updateUserStatus")->name("updateUserStatus");

    Route::resource("product-categories", "ProductCategoryController");
    Route::post("product-categories/update-category-status", "ProductCategoryController@updateStatus")->name("updateProductCategoryStatus");

    Route::resource("products", "ProductController");

    Route::get("product-images", "ProductImageController@index")->name("product-images.index");
    Route::post("product-images/store", "ProductController@storeProductImage")->name("product-images.store");
    Route::post("updateProductStatus", "ProductController@updateStatus")->name("updateProductStatus");
    Route::delete("product-images/{id}", "ProductImageController@destroy")->name("product-images.destroy");

    Route::resource("pages","PageController");
    Route::post("updatePageStatus", "PageController@updateStatus")->name("updatePageStatus");


    Route::resource("blog-categories","BlogCategoryController");
    Route::post("updateBlogCategoryStatus", "BlogCategoryController@updateStatus")->name("updateBlogCategoryStatus");


    Route::resource("blogs","BlogController");
    Route::post("updateBlogStatus", "BlogController@updateStatus")->name("updateBlogStatus");

    Route::resource("sliders", "SliderController");
    Route::post("updateSliderStatus", "SliderController@updateStatus")->name("updateSliderStatus");

    Route::resource("universities", "UniversityController");
    Route::post("updateUniversityStatus", "UniversityController@updateStatus")->name("updateUniversityStatus");

    Route::get("faculties/{id}", "FacultyController@index")->name("faculties.index");
    Route::get("faculties/create/{id}", "FacultyController@create")->name("faculties.create");
    Route::get("faculties/edit/{parentID}/{id}", "FacultyController@edit")->name("faculties.edit");
    Route::put("faculties/update/{parentID}/{id}", "FacultyController@update")->name("faculties.update");
    Route::post("faculties/store", "FacultyController@store")->name("faculties.store");
    Route::delete("faculties/delete/{id}", "FacultyController@destroy")->name("faculties.destroy");
    Route::post("updateFacultyStatus", "FacultyController@updateStatus")->name("updateFacultyStatus");
});

Route::get("logout", function (){
    Auth::logout();

    return redirect()->route("login");
});

Auth::routes(["verify" => true, "register" => false]);

Route::get('/home', 'HomeController@index')->name('home');

// FRONT ROUTES


Route::group(["namespace" => "Front"],function (){

    Route::get("/", "HomeController@index")->name("front.index");

    Route::get("kategori/{slug}", "CategoryController@index")->name("front.category");

    Route::get("blog", "BlogController@index")->name("front.get-all-blog");
    Route::get("blog/{slug}","BlogController@detail")->name("front.blog-detail");
    Route::get("blog/kategori/{slug}", "BlogController@getBlogsByCategory")->name("front.get-blogs-by-category");

    Route::post("blog/add-comment", "CommentController@store")->name("front.add-blog-comment");

    Route::get("urunler", "ProductController@index")->name("front.product-list");
    Route::get("urun/{slug}", "ProductController@detail")->name("front.product-detail");
    Route::post("urunler/ara", "ProductController@search")->name("front.search-product");

    Route::get("giris-yap", "AuthenticationController@index")->name("front.authentication");
    Route::post("giris-yap","AuthenticationController@login")->name("front.login");
    Route::post("kullanici-islemleri/kaydol","AuthenticationController@register")->name("front.register");

    Route::get("kullanici-islemleri/dogulama-kodu/{email}", "AuthenticationController@verifyCode")->name("front.verify-code");
    Route::post("kullanici-islemleri/dogrula", "AuthenticationController@verify")->name("front.verify");
    Route::post("kullanici-islemleri/tekrar-dogrula/{userId}", "AuthenticationController@reVerify")->name("front.re-verify");
    Route::get("kullanici-islemleri/cikis-yap", "AuthenticationController@logout")->name("front.logout");

    Route::get("profil/{userId}", "UserController@profile")->name("front.profile");
    Route::put("profil/güncelle/{id}", "UserController@update")->name("front.update-user");

    Route::get("urun-ekle/birinci-adim", "ProductController@create")->name("front.create-product");
    Route::post("urun-ekle/ikinci-adim", "ProductController@stepTwo")->name("front.product-step-two");
    Route::post("urun-ekle/kaydet", "ProductController@completeSteps")->name("front.product-complete-steps");

    Route::delete("urun-sil/{id}", "ProductController@destroy")->name("front.delete-product");

    Route::get("urun-duzenle/birinci-adim/{id}", "ProductController@edit")->name("front.edit-product");
    Route::put("urun-duzenle/ikinci-adim/{id}", "ProductController@editStepTwo")->name("front.edit-product-step-two");
    Route::put("urun-duzenle/tamamla/{id}", "ProductController@update")->name("front.update-product");
    Route::delete("urun-duzenle/resim-sil/{id}", "ProductController@deleteImage")->name("front.delete-product-image");

    Route::get("iletisim", "ContactController@contactPage")->name("front.contact-page");
    Route::post("iletisim/gonder", "ContactController@sendContactMessage")->name("front.contact");

    Route::post("sendMailToSeller", "ContactController@sendMailToSeller")->name("front.send-mail-to-seller");


    Route::get("testEmail", function (){
        return frontView("authentication.verify")->with(["title" => "verify", "message" => "uyarı mesajı", "user_email" => "asd"]);
    });
});

app/Http/Controllers/Panel/BlogCategoryController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Enums\BlogEnums;
use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\Repositories\Classes\BlogCategoryRepository;
use App\Traits\GeneralCrud;
use App\Traits\StatusUpdater;
use Illuminate\Http\Request;

class BlogCategoryController extends Controller
{
    use GeneralCrud, StatusUpdater;
    private $repository = null;
    private $pageEnum   = null;
    private $resource   = null;

    public function __construct()
    {
        $this->repository = new BlogCategoryRepository();
        $this->pageEnum   = new BlogEnums();
        $this->resource   = "blog-categories";
    }
    public function index()
    {
        $data = [
            "title"    => "Blog Kategorisi Yönetimi",
            "categories"    => $this->repository->getAll(),
            "isActive" => $this->pageEnum::_ACTIVE,
        ] ;

        return panelView("$this->resource.index")->with($data);
    }


    public function create()
    {
        $data = [
            "title" => "Yeni Blog Kategorisi Oluştur",
        ];

        return panelView("$this->resource.create")->with($data);
    }

    public function edit($id)
    {
        $category = $this->repository->getById($id);

        $data = [
            "title" => $category->title .  " Kategorisi Düzenleniyor",
            "category"  => $category
        ];

        return panelView("$this->resource.edit")->with($data);
    }
}

app/Http/Controllers/Panel/BlogController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Enums\BlogEnums;
use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\Blog\BlogStoreRequest;
use App\Http\Requests\Blog\BlogUpdateRequest;
use App\Repositories\Classes\BlogCategoryRepository;
use App\Repositories\Classes\BlogRepository;
use App\Traits\GeneralCrud;
use App\Traits\StatusUpdater;
use Illuminate\Http\Request;
use Mmurattcann\LaraImage\LaraImage;

class BlogController extends Controller
{
    use GeneralCrud, StatusUpdater;

    private $repository = null;
    private $categoryRepository = null;
    private $enum   = null;
    private $resource   = null;
    private $uploadPath = "uploads/blogs";
    public function __construct()
    {
        $this->repository = new BlogRepository();
        $this->categoryRepository = new BlogCategoryRepository();
        $this->enum   = new BlogEnums();
        $this->resource   = "blogs";
    }
    public function index()
    {
        $data = [
            "title"    => "Blog Yönetimi",
            "blogs"    => $this->repository->getAll(),
            "isActive" => $this->enum::_ACTIVE,
        ] ;

        return panelView("$this->resource.index")->with($data);
    }


    public function create()
    {
        $data = [
            "title" => "Yeni Sayfa Oluştur",
            "categories" => $this->categoryRepository->getAll("title", "asc")
        ];

        return panelView("$this->resource.create")->with($data);
    }

    public function edit($id)
    {
        $blog = $this->repository->getById($id);

        $data = [
            "title" => $blog->title .  " Blogu Düzenleniyor",
            "blog"  => $blog,
            "categories" => $this->categoryRepository->getAll("title","asc")
        ];

        return panelView("$this->resource.edit")->with($data);
    }

}

app/Http/Controllers/Panel/DashboardController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use App\Repositories\Classes\BlogRepository;
use App\Repositories\Classes\ProductRepository;
use App\Repositories\Classes\UniversityRepository;
use App\Repositories\Classes\UserRepository;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    private $productRepository = null;
    private $userRepository = null;
    private $blogRepository = null;
    private $universityRepository = null;

    public function __construct()
    {
        $this->productRepository = new ProductRepository();
        $this->userRepository    = new UserRepository();
        $this->blogRepository    = new BlogRepository();
        $this->universityRepository = new UniversityRepository();
    }

    public function index(){

        $lastProducts = $this->productRepository->baseQuery()->take(5)->latest()->get();
        $lastUsers    = $this->userRepository->baseQuery()->take(5)->latest()->get();

        $totalProducts = $this->productRepository->baseQuery()->count();
        $totalBlogs    = $this->blogRepository->baseQuery()->count();
        $totalUsers    = $this->userRepository->baseQuery()->count();
        $totalUniversities =  $this->universityRepository->baseQuery()->count();

        $data = [
            "title" => "Yönetim Ana Sayfa| İstatistikler",
            "lastProducts" => $lastProducts,
            "lastUsers" => $lastUsers,
            "blogCount" =>  $totalBlogs,
            "userCount" => $totalUsers,
            "productCount" => $totalProducts,
            "universityCount" => $totalUniversities
        ];
        return panelView("dashboard.index")->with($data);
    }
}

app/Http/Controllers/Panel/FacultyController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Enums\BlogEnums;
use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\Repositories\Classes\FacultyRepository;
use App\Repositories\Classes\UniversityRepository;
use App\Traits\GeneralCrud;
use App\Traits\StatusUpdater;
use Illuminate\Http\Request;

class FacultyController extends Controller
{
    use StatusUpdater;

    private $repository = null;
    private $universityRepository = null;
    private $resource = "faculties";

    public function __construct()
    {
        $this->repository = new FacultyRepository();
        $this->universityRepository = new UniversityRepository();
    }

    public function index($id){

        $university = $this->universityRepository->getById($id);
        $data = [
            "title" => $university->title. " Fakülte Listesi",
            "university" => $university,
            "faculties" => $university->faculties,
            "isActive" => BlogEnums::_ACTIVE
        ];

        return panelView("$this->resource.index")->with($data);
    }

    public function create($id){
        $university = $this->universityRepository->getById($id);

        $data = [
            "title" => "Yeni Fakülte Kaydı",
            "university" => $university
        ];

        return panelView("$this->resource.create")->with($data);
    }

    public function store(Request $request){

        $university_id = $request->get("university_id");
        $this->repository->store($request);
        return RedirectHelper::RedirectWithSuccessFlashMessage("store", "$this->resource.index", ["id" => $university_id]);
    }
    public function edit($parentID, $id){

        $university = $this->universityRepository->getById($id);
        $faculty = $this->repository->getById($id);

        $data = [
            "title" => $faculty->title. " Fakültesi Düzenleniyor",
            "university" => $university,
            "faculty" => $faculty
        ];

        return panelView("$this->resource.edit")->with($data);
    }

    public function update(Request $request, $parentID, $id){
        $university_id = $request->get("university_id");
        $this->repository->update($request, $id);
        return RedirectHelper::RedirectWithSuccessFlashMessage("store", "$this->resource.index", ["id" => $university_id]);
    }

    public function destroy($id){
        $this->repository->destroy($id);
        return response()->json(["message" => "Kayıt Başarıyla Silindi"], 200);
    }
}

app/Http/Controllers/Panel/OptionController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\Repositories\Classes\OptionRepository;
use Illuminate\Http\Request;

class OptionController extends Controller
{
    public $repository = null;
    public $resource   = "options";

    public function __construct()
    {
        $this->repository = new OptionRepository();
    }

    public function edit()
    {
        $option = $this->repository->getFirst();

        $data = [
            "title"   => "Site Ayarları",
            "option" => $option,
            "route"   => route("$this->resource.update", ["id" => $option->id])
        ];

        return panelView("$this->resource.edit")->with($data);

    }
    public function update(Request $request, $id)
    {
        $this->repository->update($request, $id);
        return RedirectHelper::RedirectWithSuccessFlashMessage("update","options.edit");
    }
}

app/Http/Controllers/Panel/ProductCategoryController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Enums\CategoryEnums;
use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\ProductCategory;
use App\Repositories\Classes\ProductCategoryRepository;
use App\Repositories\Interfaces\IProductCategoryRepository;
use App\Traits\GeneralCrud;
use App\Traits\StatusUpdater;
use Illuminate\Http\Request;

class ProductCategoryController extends Controller
{
    use GeneralCrud, StatusUpdater;

    private  $repository = null;
    private  $resource   = "product-categories";
    private  $categoryEnum = null;

    public function __construct()
    {
        $this->repository = new ProductCategoryRepository();
        $this->categoryEnum = new CategoryEnums();
    }

    public function index()
    {
        $categories = $this->repository->getAll();

        $data = [
            "title" => "Ürün Kategorisi Yönetimi",
            "categories" => $categories,
            "isActive"  => $this->categoryEnum::_ACTIVE_CATEGORY
        ];

        return panelView("$this->resource.index")->with($data);
    }


    public function create()
    {
        $data = [
            "title" => "Yeni Ürün Kategorisi Kaydı",
            "parentCategories" => $this->repository->getAllParents()
        ];

        return panelView("$this->resource.create")->with($data);
    }


    public function edit($id)
    {
        $category = $this->repository->getById($id);

        $parents  = $this->repository->getAllParents("title","asc");

        $data = [
            "title" => $category->title. " Başlıklı Kategori Düzenleniyor",
            "category" => $category,
            "parentCategories" => $parents,
        ];

        return panelView("$this->resource.edit")->with($data);
    }

}

resources/views/panel/includes/header.blade.php
<div class="app-header header py-1 d-flex">
    <div class="container-fluid">
        <div class="d-flex">
            <a class="header-brand" href="{{route("dashboard")}}">
                <img src="{{$siteLogo}}" class="header-brand-img text-center ml-5 d-none d-sm-block" alt="Spain logo"><img src="{{panelAsset("images/brand/logo.png")}}" class="header-brand-img-2 d-sm-none" alt="Spain logo">
            </a>
            <a aria-label="Hide Sidebar" class="app-sidebar__toggle" data-toggle="sidebar" href="#"></a>

            <div class="d-flex order-lg-2 ml-auto">
                <form class="form-inline mr-auto">
                    <div class="search-element">
                        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
                    </div>
                </form>

                <div class="dropdown d-none d-md-flex " >
                    <a  class="nav-link icon full-screen-link">
                        <i class="mdi mdi-arrow-expand-all"  id="fullscreen-button"></i>
                    </a>
                </div>

                <div class="dropdown">
                    <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
                        <span class="avatar avatar-md brround"><img src="{{$siteLogo}}" alt="Profile-img" class="avatar avatar-md brround"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow ">
                        <div class="text-center">
                            <a href="#" class="dropdown-item text-center font-weight-sembold user">{{Auth::user()->name}}</a>

                            <div class="dropdown-divider"></div>
                        </div>
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="e.preventDefault(); document.getElementById('logout-form').submit();" title="Çıkış Yap" >
                            <i class="dropdown-icon mdi  mdi-logout-variant"></i> Çıkış Yap
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                            @method("POST")
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/panel/includes/sidebar.blade.php
<aside class="app-sidebar">
    <div class="app-sidebar__user">
        <div class="dropdown user-pro-body">
            <div>
                <img src="{{getProfileImage(Auth::user()->image)}}" alt="user-img" class="avatar avatar-xl brround mCS_img_loaded" width="100%">
                <a href="editprofile.html" class="profile-img">
                    <span class="fa fa-pencil" aria-hidden="true"></span>
                </a>
            </div>
            <div class="user-info mb-2">
                <h4 class="font-weight-semibold text-dark mb-1">{{\Illuminate\Support\Facades\Auth::user()->name}}</h4>
                <span class="mb-0 text-muted">Admin</span>
            </div>
            <a href="{{route("options.edit")}}" title="settings" class="user-button"><i class="fa fa-cog"></i></a>
            <a href="{{ route('logout') }}" onclick="e.preventDefault(); document.getElementById('logout-form').submit();" title="Çıkış Yap" class="user-button"><i class="fa fa-power-off"></i></a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
                @method("POST")
            </form>
        </div>
    </div>

    <ul class="side-menu">
        <li>
            <a class="side-menu__item" href="{{route("dashboard")}}"><i class="side-menu__icon fa fa-desktop"></i><span class="side-menu__label">Anasayfa</span></a>
        </li>
        <li class="slide">
            <a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon mdi mdi-account-multiple"></i><span class="side-menu__label">Üniversite Yönetimi</span><i class="angle fa fa-angle-right"></i></a>
            <ul class="slide-menu">
                <li>
                    <a href="{{route("universities.index")}}" class="slide-item">Üniversite Listesi</a>
                </li>
                <li>
                    <a href="{{route("universities.create")}}" class="slide-item">Üniversite Ekle</a>
                </li>
            </ul>
        </li>
        <li class="slide">
            <a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon mdi mdi-account-multiple"></i><span class="side-menu__label">Kullanıcı Yönetimi</span><i class="angle fa fa-angle-right"></i></a>
            <ul class="slide-menu">
                <li>
                    <a href="{{route("users.index")}}" class="slide-item">Kullanıcı Listesi</a>
                </li>
                <li>
                    <a href="{{route("users.create")}}" class="slide-item">Kullanıcı Ekle</a>
                </li>
            </ul>
        </li>
        <li class="slide">
            <a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-bars"></i><span class="side-menu__label">Ürün Kategori Yönetimi</span><i class="angle fa fa-angle-right"></i></a>
            <ul class="slide-menu">
                <li>
                    <a href="{{route("product-categories.index")}}" class="slide-item">Kategori Listesi</a>
                </li>
                <li>
                    <a href="{{route("product-categories.create")}}" class="slide-item">Kategori Ekle</a>
                </li>
            </ul>
        </li>
        <li class="slide">
            <a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-cubes"></i><span class="side-menu__label">Ürün Yönetimi</span><i class="angle fa fa-angle-right"></i></a>
            <ul class="slide-menu">
                <li>
                    <a href="{{route("products.index")}}" class="slide-item">Ürün Listesi</a>
                </li>
                <li>
                    <a href="{{route("products.create")}}" class="slide-item">Ürün Ekle</a>
                </li>
            </ul>
        </li>
        <li class="slide">
            <a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-sticky-note"></i><span class="side-menu__label">Sayfa Yönetimi</span><i class="angle fa fa-angle-right"></i></a>
            <ul class="slide-menu">
                <li>
                    <a href="{{route("pages.index")}}" class="slide-item">Sayfa Listesi</a>
                </li>
                <li>
                    <a href="{{route("pages.create")}}" class="slide-item">Sayfa Ekle</a>
                </li>
            </ul>
        </li>
        <li class="slide">
            <a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-bullseye"></i><span class="side-menu__label">Blog Kategori Yönetimi</span><i class="angle fa fa-angle-right"></i></a>
            <ul class="slide-menu">
                <li>
                    <a href="{{route("blog-categories.index")}}" class="slide-item">Kategori Listesi</a>
                </li>
                <li>
                    <a href="{{route("blog-categories.create")}}" class="slide-item">Kategori Ekle</a>
                </li>
            </ul>
        </li>
        <li class="slide">
            <a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-bullseye"></i><span class="side-menu__label">Blog Yönetimi</span><i class="angle fa fa-angle-right"></i></a>
            <ul class="slide-menu">
                <li>
                    <a href="{{route("blogs.index")}}" class="slide-item">Blog Listesi</a>
                </li>
                <li>
                    <a href="{{route("blogs.create")}}" class="slide-item">Blog Ekle</a>
                </li>
            </ul>
        </li>
        <li class="slide">
            <a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-image"></i><span class="side-menu__label">Slider Yönetimi</span><i class="angle fa fa-angle-right"></i></a>
            <ul class="slide-menu">
                <li>
                    <a href="{{route("sliders.index")}}" class="slide-item">Slider Listesi</a>
                </li>
                <li>
                    <a href="{{route("sliders.create")}}" class="slide-item">Slider Ekle</a>
                </li>
            </ul>
        </li>
    </ul>
</aside>