routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// PANEL ROUTES

Route::group(["namespace" => "Panel", "prefix" => "panel", "middleware" => ["auth", "admin"]],function (){

    Route::get('dashboard', 'DashboardController@index')->name("dashboard");

    Route::get("options", "OptionController@edit")->name("options.edit");
    Route::put("options/update/{id}", "OptionController@update")->name("options.update");

    Route::resource("users", "UserController");
    Route::post("updateUserStatus", "UserController@updateUserStatus")->name("updateUserStatus");

    Route::resource("product-categories", "ProductCategoryController");
    Route::post("product-categories/update-category-status", "ProductCategoryController@updateStatus")->name("updateProductCategoryStatus");

    Route::resource("products", "ProductController");

    Route::get("product-images", "ProductImageController@index")->name("product-images.index");
    Route::post("product-images/store", "ProductController@storeProductImage")->name("product-images.store");
    Route::post("updateProductStatus", "ProductController@updateStatus")->name("updateProductStatus");
    Route::delete("product-images/{id}", "ProductImageController@destroy")->name("product-images.destroy");

    Route::resource("pages","PageController");
    Route::post("updatePageStatus", "PageController@updateStatus")->name("updatePageStatus");


    Route::resource("blog-categories","BlogCategoryController");
    Route::post("updateBlogCategoryStatus", "BlogCategoryController@updateStatus")->name("updateBlogCategoryStatus");


    Route::resource("blogs","BlogController");
    Route::post("updateBlogStatus", "BlogController@updateStatus")->name("updateBlogStatus");

    Route::resource("sliders", "SliderController");
    Route::post("updateSliderStatus", "SliderController@updateStatus")->name("updateSliderStatus");

    Route::resource("universities", "UniversityController");
    Route::post("updateUniversityStatus", "UniversityController@updateStatus")->name("updateUniversityStatus");

    Route::get("faculties/{id}", "FacultyController@index")->name("faculties.index");
    Route::get("faculties/create/{id}", "FacultyController@create")->name("faculties.create");
    Route::get("faculties/edit/{parentID}/{id}", "FacultyController@edit")->name("faculties.edit");
    Route::put("faculties/update/{parentID}/{id}", "FacultyController@update")->name("faculties.update");
    Route::post("faculties/store", "FacultyController@store")->name("faculties.store");
    Route::delete("faculties/delete/{id}", "FacultyController@destroy")->name("faculties.destroy");
    Route::post("updateFacultyStatus", "FacultyController@updateStatus")->name("updateFacultyStatus");
});

Route::get("logout", function (){
    Auth::logout();

    return redirect()->route("login");
});

Auth::routes(["verify" => true, "register" => false]);

Route::get('/home', 'HomeController@index')->name('home');

// FRONT ROUTES


Route::group(["namespace" => "Front"],function (){

    Route::get("/", "HomeController@index")->name("front.index");

    Route::get("kategori/{slug}", "CategoryController@index")->name("front.category");

    Route::get("blog", "BlogController@index")->name("front.get-all-blog");
    Route::get("blog/{slug}","BlogController@detail")->name("front.blog-detail");
    Route::get("blog/kategori/{slug}", "BlogController@getBlogsByCategory")->name("front.get-blogs-by-category");

    Route::post("blog/add-comment", "CommentController@store")->name("front.add-blog-comment");

    Route::get("urunler", "ProductController@index")->name("front.product-list");
    Route::get("urun/{slug}", "ProductController@detail")->name("front.product-detail");
    Route::post("urunler/ara", "ProductController@search")->name("front.search-product");

    Route::get("giris-yap", "AuthenticationController@index")->name("front.authentication");
    Route::post("giris-yap","AuthenticationController@login")->name("front.login");
    Route::post("kullanici-islemleri/kaydol","AuthenticationController@register")->name("front.register");

    Route::get("kullanici-islemleri/dogulama-kodu/{email}", "AuthenticationController@verifyCode")->name("front.verify-code");
    Route::post("kullanici-islemleri/dogrula", "AuthenticationController@verify")->name("front.verify");
    Route::post("kullanici-islemleri/tekrar-dogrula/{userId}", "AuthenticationController@reVerify")->name("front.re-verify");
    Route::get("kullanici-islemleri/cikis-yap", "AuthenticationController@logout")->name("front.logout");

    Route::get("profil/{userId}", "UserController@profile")->name("front.profile");
    Route::put("profil/güncelle/{id}", "UserController@update")->name("front.update-user");

    Route::get("urun-ekle/birinci-adim", "ProductController@create")->name("front.create-product");
    Route::post("urun-ekle/ikinci-adim", "ProductController@stepTwo")->name("front.product-step-two");
    Route::post("urun-ekle/kaydet", "ProductController@completeSteps")->name("front.product-complete-steps");

    Route::delete("urun-sil/{id}", "ProductController@destroy")->name("front.delete-product");

    Route::get("urun-duzenle/birinci-adim/{id}", "ProductController@edit")->name("front.edit-product");
    Route::put("urun-duzenle/ikinci-adim/{id}", "ProductController@editStepTwo")->name("front.edit-product-step-two");
    Route::put("urun-duzenle/tamamla/{id}", "ProductController@update")->name("front.update-product");
    Route::delete("urun-duzenle/resim-sil/{id}", "ProductController@deleteImage")->name("front.delete-product-image");

    Route::get("iletisim", "ContactController@contactPage")->name("front.contact-page");
    Route::post("iletisim/gonder", "ContactController@sendContactMessage")->name("front.contact");

    Route::post("sendMailToSeller", "ContactController@sendMailToSeller")->name("front.send-mail-to-seller");


    Route::get("testEmail", function (){
        return frontView("authentication.verify")->with(["title" => "verify", "message" => "uyarı mesajı", "user_email" => "asd"]);
    });
});

app/Http/Controllers/Front/ProductController.php
<?php

namespace App\Http\Controllers\Front;

use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\Repositories\Classes\ExtendedClasses\FrontProductRepositoryExtended;
use App\Repositories\Classes\ExtendedClasses\ProductRepositoryExtended;
use App\Repositories\Classes\FacultyRepository;
use App\Repositories\Classes\ProductCategoryRepository;
use App\Repositories\Classes\ProductImageRepository;
use App\Repositories\Classes\ProductRepository;
use App\Repositories\Classes\UniversityRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Murattcann\LaraImage\LaraImage;

class ProductController extends Controller
{
    private $repository = null;
    private $frontProductRepository = null;
    private $productImageRepository = null;
    private $extendedRepository = null;
    private $categoryRepository = null;
    private $universityRepository = null;
    private $facultyRepository    = null;
    private $resource = "products";

    public function __construct()
    {
        $this->repository = new ProductRepository();
        $this->frontProductRepository = new FrontProductRepositoryExtended();
        $this->productImageRepository = new ProductImageRepository();
        $this->extendedRepository = new ProductRepositoryExtended();
        $this->categoryRepository = new ProductCategoryRepository();
        $this->universityRepository = new UniversityRepository();
        $this->facultyRepository    = new FacultyRepository();
    }

    public function index(){
        $products =  $this->repository->listingMap($this->repository->getAllActive("id", "desc"));
        $categories = $this->categoryRepository->getAll("title", "asc")->toArray();

        $data = [
            "title" => "Ürünler",
            "products" => $products,
            "categories" => $categories,
            "hasCategory" => false,
            "universities" =>  $this->universityRepository->getAll("title", "asc"),
            "faculties" => $this->facultyRepository->getAll("title", "asc")
        ];

        return frontView("$this->resource.product-list")->with($data);
    }

    public function detail($slug){

        $product = $this->repository->detailMap($this->repository->getBySlug($slug));

        $similarProducts = $this->repository
            ->listingMap($this->repository->baseQuery()
                ->active()
                ->where("id", "!=", $product["id"])
                ->take(6)
                ->get());

        $data = [
            "title" => $product["title"],
            "product" => $product,
            "similarProducts" => $similarProducts
        ];

        return frontView("$this->resource.product-detail")->with($data);
    }

    public function search(Request $request){
        $request->flash();

        $title = "Ürünler";
        $category = null;
        $categoryTitle = "";

        $hasCategory = false;
        $productsByCategory = [];
        $productsByUniversity = [];
        $productsByFaculty    = [];
        $productsByLowestPrice = [];
        $productsByHighestPrice = [];
        $productsByTitle = [];

        if($request->get("category_id")){
            $categoryID = $request->get("category_id");
            $category = $this->categoryRepository->getById($categoryID);
            $categoryTitle = $category->title;
            $title =  $categoryTitle." Kategorisine Ait Ürünler";
            $productsByCategory     = $this->extendedRepository->filterByCategory($categoryID)->toArray();

            if($productsByCategory) $hasCategory = true;
        }

        if($request->get("university_id")){
            $universityID = $request->get("university_id");
            $university = $this->universityRepository->getById($universityID);
            $title      = $university->title. " Konumundaki Ürünler";
            $productsByUniversity = $this->extendedRepository->filterByUniversity($universityID)->toArray();
        }

        if($request->get("faculty_id")){
            $facultyID = $request->get("faculty_id");
            $faculty = $this->facultyRepository->getById($facultyID);
            $title      = $faculty->title. " Konumundaki Ürünler";
            $productsByFaculty = $this->extendedRepository->filterByFaculty($facultyID)->toArray();
        }

        if($request->get("lowest_price"))
            $productsByLowestPrice  = $this->extendedRepository->filterByLowestPrice($request->get("lowest_price"))->toArray();


        if($request->get("highest_price"))
            $productsByHighestPrice = $this->extendedRepository->filterByHighestPrice($request->get("highest_price"))->toArray();

        if($request->get("query")){
            $productsByTitle = $this->extendedRepository->filterByTitle($request->get("query"))->toArray();
            $title = $request->get("query"). " Aramasına İlişkin Sonuçlar";
        }

        $mergedProducts = array_merge($productsByCategory, $productsByLowestPrice, $productsByHighestPrice, $productsByTitle, $productsByUniversity, $productsByFaculty);


        $categories = $this->categoryRepository->getAll("title", "asc");


        $data = [
            "title" => $title,
            "products" => $mergedProducts,
            "categories" => $categories,
            "isSearchPage" => true,
            "hasCategory"  => $hasCategory,
            "categoryTitle" => $categoryTitle,
            "universities" =>  $this->universityRepository->getAll("title", "asc"),
            "faculties" => $this->facultyRepository->getAll("title", "asc")

        ];

        return frontView("$this->resource.product-list")->with($data);
    }

    public function create(){

        $categories = $this->categoryRepository->getAll("title", "asc");
        $universities = $this->universityRepository->getAll("title", "asc");
        $faculties = $this->facultyRepository->getAll("title", "asc");

        $data = [
            "title" => "Birinci Adım: Ürün Bilgileri",
            "categories" => $categories,
            "user" => Auth::user(),
            "universities" => $universities,
            "faculties" => $faculties
        ];

        return frontView("users.add-product")->with($data);
    }

    public function edit($id){

        $product = $this->repository->detailMap($this->repository->getById($id));
        $categories = $this->categoryRepository->getAllActive();
        $universities = $this->universityRepository->getAll("title", "asc");
        $faculties = $this->facultyRepository->getAll("title", "asc");

        $data = [
            "title" => $product["title"]. " Başlıklı Ürün Düzenleniyor",
            "product" => $product,
            "categories" => $categories,
            "user" => Auth::user(),
            "universities" => $universities,
            "faculties" => $faculties

        ];

        return frontView("users.edit-product")->with($data);
    }

    public function stepTwo(Request $request){

        Session::put("productCredentials",$request->all());
        //Session::get("productCredentials");

        $data = [
            "title" => "İkinci Adım: Ürün Resimleri",
            "user" => Auth::user(),
        ];

        return frontView("users.add-product-step-two")->with($data);
    }

    public function editStepTwo(Request $request, $id){

        Session::put("product", $request->all());

        $product = $this->repository->getById($id);

        $product->update($request->all());

        $data = [
            "title" => $product->title. " Ürününe Ait Resimler Düzenleniyor",
            "product" => $product,
            "images" => $product->images,
            "user"   => Auth::user(),

        ];

        return frontView("users.edit-product-step-two")->with($data);
    }

    public function completeSteps(Request $request){


        if($request->file("file"))
        {

            $image = $request->file("file");

            $productCredentials = Session::get("productCredentials");

            $this->frontProductRepository->storeWithArray($productCredentials);

            $this->frontProductRepository->storeFrontProductImage($image);

            //Session::flush();
            return  RedirectHelper::RedirectWithSuccessFlashMessage("store","front.profile",["userId" => Auth::user()->id]);
        }

        return redirect()->back()->with("error", "Resim yüklemeden ilan oluşturamazsınız.");

    }

    public function update(Request $request, $id){

        $this->frontProductRepository->storeFrontProductImage($request->file("file"), $id);
        return RedirectHelper::RedirectWithSuccessFlashMessage("update", "front.profile", ["userId" => Auth::user()->id]);
    }

    public function destroy($id){
        $this->repository->destroy($id);
        return response()->json(["message" => "Ürün Başarıyla Silindi"], 200);
    }

    public function deleteImage($id){

        $image =  $this->productImageRepository->baseQuery()->where("id", $id)->first();

        LaraImage::deleteUploadedFile($this->repository->uploadPath, $image->image);

        return response()->json(["message" => "Kayıt Başarıyla Silindi"]);
    }
}

app/Http/Controllers/Panel/BlogCategoryController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Enums\BlogEnums;
use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\Repositories\Classes\BlogCategoryRepository;
use App\Traits\GeneralCrud;
use App\Traits\StatusUpdater;
use Illuminate\Http\Request;

class BlogCategoryController extends Controller
{
    use GeneralCrud, StatusUpdater;
    private $repository = null;
    private $pageEnum   = null;
    private $resource   = null;

    public function __construct()
    {
        $this->repository = new BlogCategoryRepository();
        $this->pageEnum   = new BlogEnums();
        $this->resource   = "blog-categories";
    }
    public function index()
    {
        $data = [
            "title"    => "Blog Kategorisi Yönetimi",
            "categories"    => $this->repository->getAll(),
            "isActive" => $this->pageEnum::_ACTIVE,
        ] ;

        return panelView("$this->resource.index")->with($data);
    }


    public function create()
    {
        $data = [
            "title" => "Yeni Blog Kategorisi Oluştur",
        ];

        return panelView("$this->resource.create")->with($data);
    }

    public function edit($id)
    {
        $category = $this->repository->getById($id);

        $data = [
            "title" => $category->title .  " Kategorisi Düzenleniyor",
            "category"  => $category
        ];

        return panelView("$this->resource.edit")->with($data);
    }
}

resources/views/panel/products/index.blade.php
@extends("layouts.panel._layout")
@section("title")
{{$title}}
@endsection
@push("css")
    <!-- Data table css -->
    <link href="{{panelAsset("plugins/datatable/dataTables.bootstrap4.min.css")}}" rel="stylesheet" />
    <!-- Bootstrap Toggle css -->
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">

    <!---Sweetalert Css-->
    <link href="{{panelAsset("plugins/sweet-alert/jquery.sweet-modal.min.css")}}" rel="stylesheet" />
    <link href="{{panelAsset("plugins/sweet-alert/sweetalert.css")}}" rel="stylesheet" />
@endpush

@section("content")
    <div class="container">
        <ol class="breadcrumb breadcrumb-arrow mt-3">
        </ol>
        <div class="page-header">
            <h4 class="page-title">{{$title}}</h4>
            <a href="{{route("products.create")}}" class="btn btn-primary btn-lg pull-right"><i class="fa fa-user-plus"></i> Yeni Kayıt</a>

        </div>
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Kategoriler </div>
                    </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="users-table" class="table table-striped table-bordered w-100">
                            <thead>
                                <tr>
                                    <th class="wd-15p">#ID</th>
                                    <th class="wd-15p">Kapak</th>
                                    <th class="wd-10p">Başlık</th>
                                    <th class="wd-10p">Açıklama</th>
                                    <th class="wd-20p">İlan Sahibi</th>
                                    <th class="wd-20p">Kategori</th>
                                    <th class="wd-10p">Aktif Mi?</th>
                                    <th class="wd-50p">İşlemler</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($products as $product)
                                <tr id="tr-{{$product->id}}">
                                    <td>{{$product->id}}</td>
                                    <td>
                                        <img src="{{getCoverImage($product->id)}}" class="img-responsive" style="width: 100px; height: 80px;">
                                    </td>

                                    <td>{{$product->title}}</td>
                                    <td>{{getShortString($product->description,30)}}</td>
                                    <td>
                                        <span class="bg-orange rounded">
                                            {{$product->owner->name}}
                                        </span>
                                    </td>
                                    <td>
                                          <span class="bg-pink p-1 txt-white rounded">
                                           {{$product->category->title}}
                                        </span>
                                    </td>
                                    <td>
                                        <input type="checkbox"
                                               name="is_active"
                                               id="is_active"
                                               class="is_active"
                                               data-id="{{$product->id}}"
                                               data-toggle="toggle"
                                               data-on="Aktif"
                                               data-off="Pasif"
                                               data-onstyle="success"
                                               data-offstyle="danger"
                                               data-route="{{route("updateProductStatus")}}"
                                               @if($product->is_active == $isActive) checked @endif
                                        >
                                    </td>
                                    <td>
                                        <a href="{{route('products.edit', $product->id)}}" class="btn btn-outline-success" ><i class="fa fa-pencil-square-o fa-3x"></i></a>
                                        <button class="btn btn-danger delete-button" data-id="{{$product->id}}" data-route="{{route("products.destroy", $product->id)}}" >Sil</button>

                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- table-wrapper -->
            </div>
            <!-- section-wrapper -->

        </div>
    </div>
    </div>
@endsection

@push("js")
    <!-- Bootstrap Toggle -->
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

    <!-- Data tables -->
    <script src="{{panelAsset("plugins/datatable/jquery.dataTables.min.js")}}"></script>
    <script src="{{panelAsset("plugins/datatable/dataTables.bootstrap4.min.js")}}"></script>
    <script src="{{panelAsset("plugins/datatable/datatable.js")}}"></script>
    <!-- Sweet alert Plugin -->
    <script src="{{panelAsset("plugins/sweet-alert/jquery.sweet-modal.min.js")}}"></script>
    <script src="{{panelAsset("plugins/sweet-alert/sweetalert.min.js")}}"></script>
    <script src="{{panelAsset("js/sweet-alert.js")}}"></script>

    <!-- User CRUD Operations-->
    <script src="{{panelAsset("CustomOperations/productCategoryCrud.js")}}"></script>

@endpush

resources/views/panel/products/profile.blade.php
@extends("layouts._layout")
@section("title")
    {{$title}}
@endsection

@push("css")

@endpush

@section("content")
    <ol class="breadcrumb breadcrumb-arrow mt-3 mb-3">
        <li><a href="{{route("dashboard")}}">Anasayfa</a></li>
        <li class="active"><a href="#">{{$title}}</a></li>
    </ol>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{$title}}</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form action="{{route("users.updateProfile",$user->id)}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method("POST")

                                <div class="form-group">
                                    <label class="form-label">Profil Resmi</label>
                                    <img src="{{getProfileImage($user->image)}}" class="original-image" alt="{{$user->name}}" style="width: 100px; height: 100px;">
                                </div>
                                <div class="form-group">
                                    <label class="custom-control custom-radio">
                                        <input type="radio" class="custom-control-input" name="profilePictureRadio" value="1" checked>
                                        <span class="custom-control-label">Orijinali Koru</span>
                                    </label>
                                    <label class="custom-control custom-radio">
                                        <input type="radio" class="custom-control-input" name="profilePictureRadio" value="2">
                                        <span class="custom-control-label">Değiştir</span>
                                    </label>
                                </div>
                                <div class="form-group file-input-area">
                                    <div class="form-label">Profil Resmini Seç</div>
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" name="image">
                                        <label class="custom-file-label">Seç</label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Ad Soyad</label>
                                    <input type="text" class="form-control" name="name" placeholder="Ad Soyad" value="{{old("name", $user->name)}}">
                                    @error("name")
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label class="form-label">E-Posta</label>
                                    <input type="email" class="form-control" name="email" placeholder="E-Posta Adresi" value="{{old("email", $user->email)}}">
                                    @error("email")
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Telefon Numarası</label>
                                    <input type="text" class="form-control" name="phone" placeholder="Telefon Numarası" value="{{old("phone", $user->phone)}}">
                                    @error("phone")
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Şifre</label>
                                    <input type="password" class="form-control" name="password" placeholder="Şifre" >
                                    @error("password")
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Şifre Tekrar</label>
                                    <input type="password" class="form-control" name="password_confirmation" placeholder="Şifre Tekrar">
                                    @error("password_confirmation")
                                        <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                                <button class="btn btn-primary btn-lg mt-5 mb-5" type="submit">Kaydet</button>
                            </form>
                        </div>
                        <div class="col-md-6">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push("js")

    <script>
        $(function () {

            $('.file-input-area').hide();

            $('input:radio[name="profilePictureRadio"]').change(
                function(){
                    if ($(this).is(':checked') && $(this).val() == 2) {
                        $('.file-input-area').show();
                        $('.original-image').hide();
                    }else  if ($(this).is(':checked') && $(this).val() == 1) {
                        $('.file-input-area').hide();
                        $('.original-image').show();
                    }
                });
        })
    </script>
@endpush