routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// PANEL ROUTES

Route::group(["namespace" => "Panel", "prefix" => "panel", "middleware" => ["auth", "admin"]],function (){

    Route::get('dashboard', 'DashboardController@index')->name("dashboard");

    Route::get("options", "OptionController@edit")->name("options.edit");
    Route::put("options/update/{id}", "OptionController@update")->name("options.update");

    Route::resource("users", "UserController");
    Route::post("updateUserStatus", "UserController@updateUserStatus")->name("updateUserStatus");

    Route::resource("product-categories", "ProductCategoryController");
    Route::post("product-categories/update-category-status", "ProductCategoryController@updateStatus")->name("updateProductCategoryStatus");

    Route::resource("products", "ProductController");

    Route::get("product-images", "ProductImageController@index")->name("product-images.index");
    Route::post("product-images/store", "ProductController@storeProductImage")->name("product-images.store");
    Route::post("updateProductStatus", "ProductController@updateStatus")->name("updateProductStatus");
    Route::delete("product-images/{id}", "ProductImageController@destroy")->name("product-images.destroy");

    Route::resource("pages","PageController");
    Route::post("updatePageStatus", "PageController@updateStatus")->name("updatePageStatus");


    Route::resource("blog-categories","BlogCategoryController");
    Route::post("updateBlogCategoryStatus", "BlogCategoryController@updateStatus")->name("updateBlogCategoryStatus");


    Route::resource("blogs","BlogController");
    Route::post("updateBlogStatus", "BlogController@updateStatus")->name("updateBlogStatus");

    Route::resource("sliders", "SliderController");
    Route::post("updateSliderStatus", "SliderController@updateStatus")->name("updateSliderStatus");

    Route::resource("universities", "UniversityController");
    Route::post("updateUniversityStatus", "UniversityController@updateStatus")->name("updateUniversityStatus");

    Route::get("faculties/{id}", "FacultyController@index")->name("faculties.index");
    Route::get("faculties/create/{id}", "FacultyController@create")->name("faculties.create");
    Route::get("faculties/edit/{parentID}/{id}", "FacultyController@edit")->name("faculties.edit");
    Route::put("faculties/update/{parentID}/{id}", "FacultyController@update")->name("faculties.update");
    Route::post("faculties/store", "FacultyController@store")->name("faculties.store");
    Route::delete("faculties/delete/{id}", "FacultyController@destroy")->name("faculties.destroy");
    Route::post("updateFacultyStatus", "FacultyController@updateStatus")->name("updateFacultyStatus");
});

Route::get("logout", function (){
    Auth::logout();

    return redirect()->route("login");
});

Auth::routes(["verify" => true, "register" => false]);

Route::get('/home', 'HomeController@index')->name('home');

// FRONT ROUTES


Route::group(["namespace" => "Front"],function (){

    Route::get("/", "HomeController@index")->name("front.index");

    Route::get("kategori/{slug}", "CategoryController@index")->name("front.category");

    Route::get("blog", "BlogController@index")->name("front.get-all-blog");
    Route::get("blog/{slug}","BlogController@detail")->name("front.blog-detail");
    Route::get("blog/kategori/{slug}", "BlogController@getBlogsByCategory")->name("front.get-blogs-by-category");

    Route::post("blog/add-comment", "CommentController@store")->name("front.add-blog-comment");

    Route::get("urunler", "ProductController@index")->name("front.product-list");
    Route::get("urun/{slug}", "ProductController@detail")->name("front.product-detail");
    Route::post("urunler/ara", "ProductController@search")->name("front.search-product");

    Route::get("giris-yap", "AuthenticationController@index")->name("front.authentication");
    Route::post("giris-yap","AuthenticationController@login")->name("front.login");
    Route::post("kullanici-islemleri/kaydol","AuthenticationController@register")->name("front.register");

    Route::get("kullanici-islemleri/dogulama-kodu/{email}", "AuthenticationController@verifyCode")->name("front.verify-code");
    Route::post("kullanici-islemleri/dogrula", "AuthenticationController@verify")->name("front.verify");
    Route::post("kullanici-islemleri/tekrar-dogrula/{userId}", "AuthenticationController@reVerify")->name("front.re-verify");
    Route::get("kullanici-islemleri/cikis-yap", "AuthenticationController@logout")->name("front.logout");

    Route::get("profil/{userId}", "UserController@profile")->name("front.profile");
    Route::put("profil/güncelle/{id}", "UserController@update")->name("front.update-user");

    Route::get("urun-ekle/birinci-adim", "ProductController@create")->name("front.create-product");
    Route::post("urun-ekle/ikinci-adim", "ProductController@stepTwo")->name("front.product-step-two");
    Route::post("urun-ekle/kaydet", "ProductController@completeSteps")->name("front.product-complete-steps");

    Route::delete("urun-sil/{id}", "ProductController@destroy")->name("front.delete-product");

    Route::get("urun-duzenle/birinci-adim/{id}", "ProductController@edit")->name("front.edit-product");
    Route::put("urun-duzenle/ikinci-adim/{id}", "ProductController@editStepTwo")->name("front.edit-product-step-two");
    Route::put("urun-duzenle/tamamla/{id}", "ProductController@update")->name("front.update-product");
    Route::delete("urun-duzenle/resim-sil/{id}", "ProductController@deleteImage")->name("front.delete-product-image");

    Route::get("iletisim", "ContactController@contactPage")->name("front.contact-page");
    Route::post("iletisim/gonder", "ContactController@sendContactMessage")->name("front.contact");

    Route::post("sendMailToSeller", "ContactController@sendMailToSeller")->name("front.send-mail-to-seller");


    Route::get("testEmail", function (){
        return frontView("authentication.verify")->with(["title" => "verify", "message" => "uyarı mesajı", "user_email" => "asd"]);
    });
});

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $guarded = ["id"];
    protected $fillable = [
        "top_title",
        "title",
        "description",
        "image",
        "rank",
        "is_active",
        "has_button",
        "url",
        "button_title",
        "button_class"
    ];

    public function getButtonStatusAttribute($value){
        return $this->has_button == 1 ? "Var": "Yok";
    }
}

app/Http/Controllers/Panel/BlogCategoryController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Enums\BlogEnums;
use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\Repositories\Classes\BlogCategoryRepository;
use App\Traits\GeneralCrud;
use App\Traits\StatusUpdater;
use Illuminate\Http\Request;

class BlogCategoryController extends Controller
{
    use GeneralCrud, StatusUpdater;
    private $repository = null;
    private $pageEnum   = null;
    private $resource   = null;

    public function __construct()
    {
        $this->repository = new BlogCategoryRepository();
        $this->pageEnum   = new BlogEnums();
        $this->resource   = "blog-categories";
    }
    public function index()
    {
        $data = [
            "title"    => "Blog Kategorisi Yönetimi",
            "categories"    => $this->repository->getAll(),
            "isActive" => $this->pageEnum::_ACTIVE,
        ] ;

        return panelView("$this->resource.index")->with($data);
    }


    public function create()
    {
        $data = [
            "title" => "Yeni Blog Kategorisi Oluştur",
        ];

        return panelView("$this->resource.create")->with($data);
    }

    public function edit($id)
    {
        $category = $this->repository->getById($id);

        $data = [
            "title" => $category->title .  " Kategorisi Düzenleniyor",
            "category"  => $category
        ];

        return panelView("$this->resource.edit")->with($data);
    }
}

app/Http/Controllers/Panel/BlogController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Enums\BlogEnums;
use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\Blog\BlogStoreRequest;
use App\Http\Requests\Blog\BlogUpdateRequest;
use App\Repositories\Classes\BlogCategoryRepository;
use App\Repositories\Classes\BlogRepository;
use App\Traits\GeneralCrud;
use App\Traits\StatusUpdater;
use Illuminate\Http\Request;
use Mmurattcann\LaraImage\LaraImage;

class BlogController extends Controller
{
    use GeneralCrud, StatusUpdater;

    private $repository = null;
    private $categoryRepository = null;
    private $enum   = null;
    private $resource   = null;
    private $uploadPath = "uploads/blogs";
    public function __construct()
    {
        $this->repository = new BlogRepository();
        $this->categoryRepository = new BlogCategoryRepository();
        $this->enum   = new BlogEnums();
        $this->resource   = "blogs";
    }
    public function index()
    {
        $data = [
            "title"    => "Blog Yönetimi",
            "blogs"    => $this->repository->getAll(),
            "isActive" => $this->enum::_ACTIVE,
        ] ;

        return panelView("$this->resource.index")->with($data);
    }


    public function create()
    {
        $data = [
            "title" => "Yeni Sayfa Oluştur",
            "categories" => $this->categoryRepository->getAll("title", "asc")
        ];

        return panelView("$this->resource.create")->with($data);
    }

    public function edit($id)
    {
        $blog = $this->repository->getById($id);

        $data = [
            "title" => $blog->title .  " Blogu Düzenleniyor",
            "blog"  => $blog,
            "categories" => $this->categoryRepository->getAll("title","asc")
        ];

        return panelView("$this->resource.edit")->with($data);
    }

}

app/Http/Controllers/Panel/DashboardController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use App\Repositories\Classes\BlogRepository;
use App\Repositories\Classes\ProductRepository;
use App\Repositories\Classes\UniversityRepository;
use App\Repositories\Classes\UserRepository;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    private $productRepository = null;
    private $userRepository = null;
    private $blogRepository = null;
    private $universityRepository = null;

    public function __construct()
    {
        $this->productRepository = new ProductRepository();
        $this->userRepository    = new UserRepository();
        $this->blogRepository    = new BlogRepository();
        $this->universityRepository = new UniversityRepository();
    }

    public function index(){

        $lastProducts = $this->productRepository->baseQuery()->take(5)->latest()->get();
        $lastUsers    = $this->userRepository->baseQuery()->take(5)->latest()->get();

        $totalProducts = $this->productRepository->baseQuery()->count();
        $totalBlogs    = $this->blogRepository->baseQuery()->count();
        $totalUsers    = $this->userRepository->baseQuery()->count();
        $totalUniversities =  $this->universityRepository->baseQuery()->count();

        $data = [
            "title" => "Yönetim Ana Sayfa| İstatistikler",
            "lastProducts" => $lastProducts,
            "lastUsers" => $lastUsers,
            "blogCount" =>  $totalBlogs,
            "userCount" => $totalUsers,
            "productCount" => $totalProducts,
            "universityCount" => $totalUniversities
        ];
        return panelView("dashboard.index")->with($data);
    }
}

app/Http/Controllers/Panel/FacultyController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Enums\BlogEnums;
use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\Repositories\Classes\FacultyRepository;
use App\Repositories\Classes\UniversityRepository;
use App\Traits\GeneralCrud;
use App\Traits\StatusUpdater;
use Illuminate\Http\Request;

class FacultyController extends Controller
{
    use StatusUpdater;

    private $repository = null;
    private $universityRepository = null;
    private $resource = "faculties";

    public function __construct()
    {
        $this->repository = new FacultyRepository();
        $this->universityRepository = new UniversityRepository();
    }

    public function index($id){

        $university = $this->universityRepository->getById($id);
        $data = [
            "title" => $university->title. " Fakülte Listesi",
            "university" => $university,
            "faculties" => $university->faculties,
            "isActive" => BlogEnums::_ACTIVE
        ];

        return panelView("$this->resource.index")->with($data);
    }

    public function create($id){
        $university = $this->universityRepository->getById($id);

        $data = [
            "title" => "Yeni Fakülte Kaydı",
            "university" => $university
        ];

        return panelView("$this->resource.create")->with($data);
    }

    public function store(Request $request){

        $university_id = $request->get("university_id");
        $this->repository->store($request);
        return RedirectHelper::RedirectWithSuccessFlashMessage("store", "$this->resource.index", ["id" => $university_id]);
    }
    public function edit($parentID, $id){

        $university = $this->universityRepository->getById($id);
        $faculty = $this->repository->getById($id);

        $data = [
            "title" => $faculty->title. " Fakültesi Düzenleniyor",
            "university" => $university,
            "faculty" => $faculty
        ];

        return panelView("$this->resource.edit")->with($data);
    }

    public function update(Request $request, $parentID, $id){
        $university_id = $request->get("university_id");
        $this->repository->update($request, $id);
        return RedirectHelper::RedirectWithSuccessFlashMessage("store", "$this->resource.index", ["id" => $university_id]);
    }

    public function destroy($id){
        $this->repository->destroy($id);
        return response()->json(["message" => "Kayıt Başarıyla Silindi"], 200);
    }
}

app/Http/Controllers/Panel/OptionController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\Repositories\Classes\OptionRepository;
use Illuminate\Http\Request;

class OptionController extends Controller
{
    public $repository = null;
    public $resource   = "options";

    public function __construct()
    {
        $this->repository = new OptionRepository();
    }

    public function edit()
    {
        $option = $this->repository->getFirst();

        $data = [
            "title"   => "Site Ayarları",
            "option" => $option,
            "route"   => route("$this->resource.update", ["id" => $option->id])
        ];

        return panelView("$this->resource.edit")->with($data);

    }
    public function update(Request $request, $id)
    {
        $this->repository->update($request, $id);
        return RedirectHelper::RedirectWithSuccessFlashMessage("update","options.edit");
    }
}

app/Http/Controllers/Panel/ProductCategoryController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Enums\CategoryEnums;
use App\Helpers\RedirectHelper\RedirectHelper;
use App\Http\Controllers\Controller;
use App\ProductCategory;
use App\Repositories\Classes\ProductCategoryRepository;
use App\Repositories\Interfaces\IProductCategoryRepository;
use App\Traits\GeneralCrud;
use App\Traits\StatusUpdater;
use Illuminate\Http\Request;

class ProductCategoryController extends Controller
{
    use GeneralCrud, StatusUpdater;

    private  $repository = null;
    private  $resource   = "product-categories";
    private  $categoryEnum = null;

    public function __construct()
    {
        $this->repository = new ProductCategoryRepository();
        $this->categoryEnum = new CategoryEnums();
    }

    public function index()
    {
        $categories = $this->repository->getAll();

        $data = [
            "title" => "Ürün Kategorisi Yönetimi",
            "categories" => $categories,
            "isActive"  => $this->categoryEnum::_ACTIVE_CATEGORY
        ];

        return panelView("$this->resource.index")->with($data);
    }


    public function create()
    {
        $data = [
            "title" => "Yeni Ürün Kategorisi Kaydı",
            "parentCategories" => $this->repository->getAllParents()
        ];

        return panelView("$this->resource.create")->with($data);
    }


    public function edit($id)
    {
        $category = $this->repository->getById($id);

        $parents  = $this->repository->getAllParents("title","asc");

        $data = [
            "title" => $category->title. " Başlıklı Kategori Düzenleniyor",
            "category" => $category,
            "parentCategories" => $parents,
        ];

        return panelView("$this->resource.edit")->with($data);
    }

}

resources/views/panel/sliders/index.blade.php
@extends("layouts.panel._layout")
@section("title")
{{$title}}
@endsection
@push("css")
    <!-- Data table css -->
    <link href="{{panelAsset("plugins/datatable/dataTables.bootstrap4.min.css")}}" rel="stylesheet" />
    <!-- Bootstrap Toggle css -->
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">

    <!---Sweetalert Css-->
    <link href="{{panelAsset("plugins/sweet-alert/jquery.sweet-modal.min.css")}}" rel="stylesheet" />
    <link href="{{panelAsset("plugins/sweet-alert/sweetalert.css")}}" rel="stylesheet" />
@endpush

@section("content")
    <div class="container">
        <ol class="breadcrumb breadcrumb-arrow mt-3">
        </ol>
        <div class="page-header">
            <h4 class="page-title">{{$title}}</h4>
            <a href="{{route("sliders.create")}}" class="btn btn-primary btn-lg pull-right"><i class="fa fa-user-plus"></i> Yeni Kayıt</a>

        </div>
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">{{$title}} </div>
                    </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="users-table" class="table table-striped table-bordered w-100 datatable">
                            <thead>
                                <tr>
                                    <th class="wd-15p">#ID</th>
                                    <th class="wd-15p">Görsel</th>
                                    <th class="wd-15p">Başlık</th>
                                    <th class="wd-10p">Sıra</th>
                                    <th class="wd-10p">Buton Durumu</th>
                                    <th class="wd-10p">Durum</th>
                                    <th class="wd-50p">İşlemler</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($sliders as $slider)
                                <tr id="tr-{{$slider->id}}">
                                    <td>{{$slider->id}}</td>
                                    <td>
                                        <img src="{{getSliderImage($slider->image)}}" alt="{{$slider->title}}" class="img-responsive" style="width: 125px; height: 100px">
                                    </td>
                                    <td>{{$slider->title}}</td>
                                    <td>{{$slider->rank}}</td>
                                    <td>{{$slider->button_status}}</td>
                                    <td>
                                        <input type="checkbox"
                                               name="is_active"
                                               id="is_active"
                                               class="is_active"
                                               data-id="{{$slider->id}}"
                                               data-toggle="toggle"
                                               data-on="Aktif"
                                               data-off="Pasif"
                                               data-onstyle="success"
                                               data-offstyle="danger"
                                               data-route="{{route("updateSliderStatus")}}"
                                               @if($slider->is_active == $isActive) checked @endif
                                        >
                                    </td>
                                    <td>
                                        <a href="{{route('sliders.edit', $slider->id)}}" class="btn btn-outline-success" ><i class="fa fa-pencil-square-o fa-3x"></i></a>
                                        <button class="btn btn-danger delete-button" data-id="{{$slider->id}}" data-route="{{route("sliders.destroy", $slider->id)}}" >Sil</button>

                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- table-wrapper -->
            </div>
            <!-- section-wrapper -->

        </div>
    </div>
    </div>
@endsection

@push("js")
    <!-- Bootstrap Toggle -->
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

    <!-- Data tables -->
    <script src="{{panelAsset("plugins/datatable/jquery.dataTables.min.js")}}"></script>
    <script src="{{panelAsset("plugins/datatable/dataTables.bootstrap4.min.js")}}"></script>
    <script src="{{panelAsset("plugins/datatable/datatable.js")}}"></script>
    <!-- Sweet alert Plugin -->
    <script src="{{panelAsset("plugins/sweet-alert/jquery.sweet-modal.min.js")}}"></script>
    <script src="{{panelAsset("plugins/sweet-alert/sweetalert.min.js")}}"></script>
    <script src="{{panelAsset("js/sweet-alert.js")}}"></script>

    <!-- User CRUD Operations-->
    <script src="{{panelAsset("CustomOperations/userCrud.js")}}"></script>

@endpush